// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("NFastText")>]
[<assembly: AssemblyProductAttribute("NFastText")>]
[<assembly: AssemblyDescriptionAttribute("fast text classification library based on facebook's fastText library implementation.")>]
[<assembly: AssemblyVersionAttribute("0.0.4")>]
[<assembly: AssemblyFileVersionAttribute("0.0.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "NFastText"
    let [<Literal>] AssemblyProduct = "NFastText"
    let [<Literal>] AssemblyDescription = "fast text classification library based on facebook's fastText library implementation."
    let [<Literal>] AssemblyVersion = "0.0.4"
    let [<Literal>] AssemblyFileVersion = "0.0.4"
