// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ConsoleTest")>]
[<assembly: AssemblyProductAttribute("NFastText")>]
[<assembly: AssemblyDescriptionAttribute("fast text classification library based on facebook's fastText library implementation.")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] Version = "1.0"
    let [<Literal>] InformationalVersion = "1.0"
